
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Set;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author black
 */
public class Ventana extends javax.swing.JFrame {
    //declaracion de variables globales
    String sexo ="";
    Date feNac = null;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        btnCurp.setVisible(false);
        lblWarning.setVisible(false);
        

        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAPaterno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAMaterno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtANac = new javax.swing.JTextField();
        cbMes = new javax.swing.JComboBox<>();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        chbTerminos = new javax.swing.JCheckBox();
        btnCurp = new javax.swing.JButton();
        tgBRobot = new javax.swing.JToggleButton();
        lblWarning = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblWarning4 = new javax.swing.JLabel();
        lblWarning3 = new javax.swing.JLabel();
        lblWarning2 = new javax.swing.JLabel();
        lblWarning1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(51, 153, 0));
        pnlPrincipal.setForeground(new java.awt.Color(0, 51, 0));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre(s)*:");

        txtNombres.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setText("Primer apellido*:");

        txtAPaterno.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel3.setText("Segundo Apellido:");

        txtAMaterno.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel4.setText("Estado*:");

        cbEstado.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el estado", "NT-Nayarit", "MC-Michoacan", "BC-Baja California" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel1.setText("Generador de CURP");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel6.setText("Día de nacimiento*:");

        cbDia.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar el día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel7.setText("Año de nacimiento*:");

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel9.setText("Mes de nacimiento*:");

        txtANac.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N

        cbMes.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar el mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        bgSexo.add(rbHombre);
        rbHombre.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        rbHombre.setText("Hombre");
        rbHombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbHombreMouseClicked(evt);
            }
        });

        bgSexo.add(rbMujer);
        rbMujer.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        rbMujer.setText("Mujer");
        rbMujer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMujerMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel10.setText("Sexo*:");

        chbTerminos.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        chbTerminos.setText("He leído y acepto los términos y condiciones de uso");

        btnCurp.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btnCurp.setText("Generar Curp");
        btnCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurpActionPerformed(evt);
            }
        });

        tgBRobot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Robot.PNG"))); // NOI18N
        tgBRobot.setRolloverEnabled(true);
        tgBRobot.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/nRobot.PNG"))); // NOI18N
        tgBRobot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tgBRobotMouseClicked(evt);
            }
        });

        lblWarning.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lblWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning.setText("Debes aceptar los terminos para poder continuar.");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        lblWarning4.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lblWarning4.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning4.setText("a ser XX, ya que son caracteres asignados por gobierno.");

        lblWarning3.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lblWarning3.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning3.setText("un robot, y listo, podremos saber nuestra curp, los dos ultmos digitos pasan");

        lblWarning2.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lblWarning2.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning2.setText("introducir nuestros datos, aceptar los terminos, confirmar que no somos");

        lblWarning1.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        lblWarning1.setForeground(new java.awt.Color(255, 0, 0));
        lblWarning1.setText("Este programa sirve para poder generar nuestra curp, solo tenemos que");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarning1)
                    .addComponent(lblWarning2)
                    .addComponent(lblWarning3)
                    .addComponent(lblWarning4))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblWarning1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarning2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarning3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWarning4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWarning))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnCurp)))
                .addGap(0, 179, Short.MAX_VALUE))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbTerminos, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtAMaterno)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addComponent(rbHombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rbMujer))
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbDia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtAPaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtANac, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgBRobot, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel1))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtANac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chbTerminos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgBRobot, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCurp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void btnCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurpActionPerformed
        if(chbTerminos.isSelected()){
            lblWarning.setVisible(false);
            String p = txtANac.getText()+"-"+cbMes.getItemAt(cbMes.getSelectedIndex())+"-"+cbDia.getItemAt(cbDia.getSelectedIndex());
            feNac = generarFecha(p);
            String sSexo = "";
            if(rbHombre.isSelected() || rbMujer.isSelected()){
               sSexo = sexo;
            }
            String sEstado=cbEstado.getItemAt(cbEstado.getSelectedIndex());
            if(!validaCampo(txtAPaterno)) return;
            if(!validaCampo(txtAMaterno)) return;
            if(!validaCampo(txtNombres)) return;
            if(!validaFecha())return;
            if(cbEstado.getSelectedIndex()==0){
                 showMessageDialog(this, "Seleccione estado"); return;
            }  
            String datosPersonales = "Tus datos son los siguientes: \n"
                    + "Nombre(s)*: "+txtNombres.getText()+
                    "\nPrimer Apellido: "+txtAPaterno.getText()+
                    "\nSegundo Apellido: "+txtAMaterno.getText()+
                    "\nSexo: "+sSexo+
                    "\nFecha de nacimiento: "+p+
                    "\nEstado: "+sEstado
                    +"\n¿Deseas continuar?";
            if (JOptionPane.showConfirmDialog(this, datosPersonales, "Atención" ,JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                String curp=pVocal(txtAPaterno.getText().toUpperCase())+pLetraM(txtAMaterno.getText().toUpperCase())+pNombre(txtNombres.getText().toUpperCase())+feNac(p)+sSexo+combEstado(sEstado);
                curp=curp+getPCP(txtAPaterno.getText().toUpperCase())+getPCM(txtAMaterno.getText().toUpperCase())+getPCN(txtNombres.getText().toUpperCase())+"XX";
                showMessageDialog(this, "Tu curp es: "+curp); 
                restablecer();
            }
        }else{
            lblWarning.setVisible(true);
        }
    }//GEN-LAST:event_btnCurpActionPerformed
    private void restablecer(){
                tgBRobot.doClick();
                chbTerminos.doClick();
                btnCurp.setVisible(false);
                bgSexo.clearSelection();
                txtNombres.setText("");
                txtAPaterno.setText("");
                txtAMaterno.setText("");
                cbDia.setSelectedIndex(0);
                cbMes.setSelectedIndex(0);
                txtANac.setText("");
                cbEstado.setSelectedIndex(0);
    }
    private Date generarFecha(String p){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date fecha = null;
        try {
            fecha = dateFormat.parse(p);
        }catch (ParseException ex){
           showMessageDialog(this, ex);
        }
        return fecha;
    }
    private void rbHombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbHombreMouseClicked
        sexo = "";
        sexo ="H";
    }//GEN-LAST:event_rbHombreMouseClicked

    private void rbMujerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMujerMouseClicked
        sexo = "";
        sexo ="M";
        
    }//GEN-LAST:event_rbMujerMouseClicked

    private void tgBRobotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgBRobotMouseClicked
        if(tgBRobot.isSelected()){
            btnCurp.setVisible(true);
        }
    }//GEN-LAST:event_tgBRobotMouseClicked

        public void fechaInvalida()throws CurpException{
        if(feNac==null)throw new CurpException("Fecha invalida");
        Date fecha=new Date();
        if(feNac.after(fecha))throw new CurpException("Fecha posterior a la actual");
    }
    public boolean validaFecha(){
        try{fechaInvalida();}
        catch(CurpException e){showMessageDialog(this, e.getMessage()); return false; }
        return true;
    }
    public String feNac(String p){
        String anho="";
        String mes="";
        String dia="";
        String F="";
        anho=p.split("-")[0];
        mes=p.split("-")[1];
        dia=p.split("-")[2];
        return F=anho.substring(2,4)+mes+dia;     
    }
        public String combEstado(String cbEstado){
            String c=cbEstado;
        return c.substring(0,2);     
    }
        public String getPCP(String cad){
        cad=cad.replaceAll("DE ","");
        cad=cad.replaceAll("LOS ","");
        cad=cad.replaceAll("DEL ","");
        cad=cad.replaceAll("LA ","");
        cad=cad.replaceAll("Ñ","X");
        String v="AEIOU";
        for (int i = 1; i < cad.length(); i++) {
            if(v.indexOf(cad.substring(i,i+1))==-1){return cad.substring(i,i+1);}
            
        }
        return "";
    }
     public String getPCM(String cad){
        cad=cad.replaceAll("DE ","");
        cad=cad.replaceAll("LOS ","");
        cad=cad.replaceAll("DEL ","");
        cad=cad.replaceAll("LA ","");
        cad=cad.replaceAll("Ñ","X");
        String v="AEIOU";
        for (int i = 1; i < cad.length(); i++) {
            if(v.indexOf(cad.substring(i,i+1))==-1){return cad.substring(i,i+1);}
            
        }
        return "";
    }
        public String getPCN(String cad){
        cad=cad.replaceAll("DE ","");
        cad=cad.replaceAll("DEL ","");
        cad=cad.replaceAll("LA ","");
        cad=cad.replaceAll("LOS ","");
        cad=cad.replaceAll("Ñ","X");
        String c[ ]=cad.split(" ");
        String v="AEIOU";
        if(c.length==1){
            return getPCM(c[0]);
        }
        if(c[0].equals("JOSE") || c[0].equals("MARIA")){
            for (int i = 1; i < c[1].length(); i++) {
            if(v.indexOf(c[1].substring(i,i+1))==-1){return c[1].substring(i,i+1);}
            }
        }
        for (int i = 1; i < c[0].length(); i++) {
            if(v.indexOf(c[0].substring(i,i+1))==-1){return c[0].substring(i,i+1);} 
        }
        return "";
    } 
    public String pNombre(String cad){
        cad=cad.replaceAll("DE ","");
        cad=cad.replaceAll("DEL ","");
        cad=cad.replaceAll("LA ","");
        cad=cad.replaceAll("LOS ","");
        cad=cad.replaceAll("Ñ","X");
        String c[ ]=cad.split(" ");
        if(c.length==1) return cad.substring(0,1);
        if(c[0].equals("JOSE") || c[0].equals("MARIA")) return c[1].substring(0,1);
        return c[0].substring(0,1);

    }
    public String pVocal(String cad){
        cad=cad.replaceAll("DE ","");
        cad=cad.replaceAll("LOS ","");
        cad=cad.replaceAll("DEL ","");
        cad=cad.replaceAll("LA ","");
        String c=cad.substring(0, 1);
        String v="aeiouAEIOU";
        for (int i = 1; i < cad.length(); i++) {
            if(v.indexOf(cad.substring(i,i+1))!=-1){c=c+cad.substring(i,i+1);break;}
            
        }
        return c;
    }
        public String pLetraM(String cad){
        cad=cad.replaceAll("DE ","");
        cad=cad.replaceAll("DEL ","");
        cad=cad.replaceAll("LA ","");
        cad=cad.replaceAll("LOS ","");
        String c=cad.substring(0, 1);
        return c;
    }
    public boolean validaCampo(JTextField t){
    try{
        textVacio(t);
        }catch( CurpException e){
            showMessageDialog(this, e.getMessage()); t.requestFocus();return false;         
        }
       return true;
    }
    private void textVacio(JTextField t)throws CurpException{
        if(t.getText().equals("")) throw new CurpException("Campo vacio.");   
    }
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btnCurp;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JCheckBox chbTerminos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JLabel lblWarning1;
    private javax.swing.JLabel lblWarning2;
    private javax.swing.JLabel lblWarning3;
    private javax.swing.JLabel lblWarning4;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JToggleButton tgBRobot;
    private javax.swing.JTextField txtAMaterno;
    private javax.swing.JTextField txtANac;
    private javax.swing.JTextField txtAPaterno;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
